version: '2'
services:
 web1:
  build: ./requestFrom/WebServisai
  command: python ./requestFrom/WebServisai/app.py runserver 0.0.0.0:81
  ports:
   - "81:5000"
  volumes:
   - .:/code
 web:
  build: .
  command: python app.py
  ports:
   - "80:5000"
  volumes:
   - .:/code
  links:
   - web1
